### ISSUE TITLE
'grep' is not recognized

### ISSUE THREAD

**Issue by gabzdyl** [Fried-Chicken/ghost-static-site-generator#25]
When executing gssg command I get following error: 

Error: Command failed: wget --help | grep "show-progress" || true
'grep' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at shouldShowProgress (C:\Users\Me\AppData\Roaming\npm\node_modules\ghost-static-site-generator\src\constants\OPTIONS.js:15:32)
    at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\ghost-static-site-generator\src\constants\OPTIONS.js:39:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by Fried-Chicken** [comment]
Hey @gabzdyl Which version of windows are you using?

**Comment by GreyBeardDoer** [comment]
I'm still getting this error. Did you resolve this?
